
[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 1
blur = true
startup_mode = "Maximized"
[font]
normal.family = "RobotoMono Nerd Font"
size = 14
